FROM python:3.10.6-alpine

WORKDIR /usr/src/app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

RUN chmod a+x ./*.py

ENTRYPOINT ["python", "-u", "./ErnieDingBot.py" ]